SELECT * FROM SW.MAQUINA

ALTER TABLE SW.MAQUINA MODIFY COLUMN idmaquina INT auto_increment

ALTER TABLE SW.MAQUINA AUTO_INCREMENT = 1;

ALTER TABLE SW.MAQUINAhasejercicio
DROP FOREIGN KEY FK_IDMAQUINA